# Environment Menu Configuration
# 環境設定メニュー設定

# メニューを開いた時の効果音
open_sound:
  sound: "BLOCK_CHEST_OPEN"
  pitch: 1.0

# アイコン設定
icons:
  # 戻るボタン
  back:
    material: ARROW
    sound: "UI_BUTTON_CLICK"
    pitch: 2.0

  # ポイント不足
  insufficient_points:
    sound: "BLOCK_ANVIL_PLACE"
    pitch: 1.0

  # 重力変更
  gravity_change:
    sound: "BLOCK_ANVIL_USE"
    pitch: 1.0

  # バイオーム変更
  biome_change:
    sound: "ITEM_BOTTLE_EMPTY"
    pitch: 1.0

  # 天候変更
  weather_change:
    sound: "ENTITY_PLAYER_LEVELUP"
    pitch: 2.0
